config/routes.rb
Rails.application.routes.draw do
  root 'slides#index'
  resources :slides, only: [:new, :create]

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  http_basic_authenticate_with name: ENV['HTTP_USERNAME'], password: ENV['HTTP_PASSWORD'], except: :index

  def index
    @slides = Slide.all
  end

  def new
    @slide = Slide.new
  end

  def create
    @slide = Slide.new(slide_params)

    if @slide.save
      redirect_to root_url, notice: 'Slide was successfully created.'
    else
      render :new
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
  def slide_tag(slide, size)
    if Rails.env.production?
      image_tag "#{ENV['CDN_HOST']}/#{size}#{slide.image.path}"
    else
      image_tag slide.image
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SarmaAssets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/slides/_form.html.erb
<%= form_for @slide, multipart: true do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/index.html.erb
<div id="slider" class="flexslider">
  <ul class="slides">
    <% @slides.each do |slide| %>
      <li><%= slide_tag(slide, '1170x') %></li>
    <% end %>
  </ul>
</div>

<div id="carousel" class="flexslider">
  <ul class="slides">
    <% @slides.each do |slide| %>
      <li><%= slide_tag(slide, '210x') %></li>
    <% end %>
  </ul>
</div>

<%= link_to 'New Slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New Slide</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>